<<<<<<< HEAD
# version: "3.8"
=======
version: "2.2"
>>>>>>> d317a67143fb514fe922c4eab02cf661f6772dff

networks:
  intra:
    driver: bridge #driver connection type is bridge
    ipam: 
      driver: default
      config:
        - subnet: 172.31.0.0/16 #docker network

volumes:
  wordpress-volume:
    name: wordpress-volume
    driver: local
    driver_opts:
      type: none
      device: /home/hesong/data/wordpress #share with host
      o: bind

  mariadb-volume:
    name: mariadb-volume
    driver: local
    driver_opts:
      type: none
      device: /home/hesong/data/mariadb #share with host
      o: bind

services:
  
  mariadb:
    build: ./requirements/mariadb
<<<<<<< HEAD
    restart: always
    container_name: mariadb
    expose:
        - "3306"
=======
    container_name: mariadb
    expose:
      - "3306"
>>>>>>> d317a67143fb514fe922c4eab02cf661f6772dff
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      intra:
        ipv4_address: 172.31.0.13
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
<<<<<<< HEAD
    restart: always
    container_name: wordpress
    expose:
        - "9000"
    volumes:
      - wordpress-volume:/var/www/html
=======
    container_name: wordpress
    volumes:
      - wordpress-volume:/var/www/html
    expose:
      - "9000"
>>>>>>> d317a67143fb514fe922c4eab02cf661f6772dff
    networks:
      intra:
        ipv4_address: 172.31.0.11
    env_file:
      - .env # env path
<<<<<<< HEAD
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    restart: always
=======

  nginx:
    build: ./requirements/nginx
>>>>>>> d317a67143fb514fe922c4eab02cf661f6772dff
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      intra:
        ipv4_address: 172.31.0.12

